from typing import Final

USER_BALANCE_PRECISION: Final = 1
USER_PHOTO_SUBMISSION_REWARD: Final = int(1000 * USER_BALANCE_PRECISION)
PHOTO_AMOUNT_FOR_UNIQUINESS_CHECK: Final = 1
PHOTO_VERIFICATION_MAX_RETRIES: Final = 10
PHOTO_UNIQUINESS_DIFFERENCE_THRESHOLD: Final = 0  # 0..100


INIT_DATA_EXPIRE_HOURS: Final = 24
REFERAL_PARAM_PREFIX: Final = "?startapp=friendId"
INVITATION_REWARD: Final = 1_000 * USER_BALANCE_PRECISION
INVITATION_PREMIUM_REWARD: Final = 5_000 * USER_BALANCE_PRECISION
INVITOR_REWARD_PERCENT: Final = 10
INVITOR_SECONDARY_REWARD_PERCENT: Final = 2

VIDEO_FRAMERATE: Final = 2
VIDEO_MIN_PHOTOS: Final = 10
VIDEO_MAX_PHOTOS: Final = 100

VIDEO_TOKENS_PER_PHOTO: Final = int(10_000 * USER_BALANCE_PRECISION)
