"""Video model fk

Revision ID: 227a355b8874
Revises: f3aa37c1bc9a
Create Date: 2024-07-15 18:10:57.161883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227a355b8874'
down_revision: Union[str, None] = 'f3aa37c1bc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'video_metadata', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_metadata', type_='unique')
    # ### end Alembic commands ###
