"""Added new user info

Revision ID: 527bf0653c43
Revises: 1db99efee1cb
Create Date: 2024-07-11 08:51:45.652321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527bf0653c43'
down_revision: Union[str, None] = '1db99efee1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('users', sa.Column('language', sa.String(), nullable=False, server_default="ru"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
