"""Add tables

Revision ID: 64e8478a22cd
Revises: 702696cd6dc8
Create Date: 2024-07-07 08:17:34.384565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64e8478a22cd"
down_revision: Union[str, None] = "702696cd6dc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("verification_photo_metadata_id", sa.Uuid(), nullable=True),
        sa.Column("profile_photo_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "photo_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("analyzis_data__angry", sa.Float(), nullable=False),
        sa.Column("analyzis_data__disgust", sa.Float(), nullable=False),
        sa.Column("analyzis_data__fear", sa.Float(), nullable=False),
        sa.Column("analyzis_data__happy", sa.Float(), nullable=False),
        sa.Column("analyzis_data__neutral", sa.Float(), nullable=False),
        sa.Column("analyzis_data__sad", sa.Float(), nullable=False),
        sa.Column("analyzis_data__surprise", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        "user_verification_photo_id_pk",
        "users",
        "photo_metadata",
        ["verification_photo_metadata_id"],
        ["id"],
    )

    # ### end Alembic commands ###


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("photo_metadata")
    # ### end Alembic commands ###
