"""Store profile photos locally

Revision ID: c59cfc849958
Revises: 315348e90206
Create Date: 2024-07-08 10:39:41.159686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59cfc849958'
down_revision: Union[str, None] = '315348e90206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_path', sa.String(), nullable=True))
    op.drop_column('users', 'profile_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_photo_path')
    # ### end Alembic commands ###
