"""Video model

Revision ID: f3aa37c1bc9a
Revises: d07ad8f99041
Create Date: 2024-07-15 18:08:59.235497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3aa37c1bc9a'
down_revision: Union[str, None] = 'd07ad8f99041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('publication_reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('game_status', 'total_users',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('game_status', 'total_balance',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_status', 'total_balance',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('game_status', 'total_users',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_table('video_metadata')
    # ### end Alembic commands ###
